name: pangle_flutter
description: A Flutter plugin that supports ByteDance Pangle SDK on Android and iOS. Such as Splash Ads, Rewarded Video Ads, etc.
version: 0.1.2
homepage: https://github.com/nullptrX/pangle_flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.github.nullptrx.pangleflutter
        pluginClass: PangleFlutterPlugin
      ios:
        pluginClass: PangleFlutterPlugin

